var mongoose = require('mongoose'),
    Schema = mongoose.Schema;

var riesgosSchema = new Schema({
    F1: Number,
    F2: Number,
    F3: Number,
    F4: Number,
    F5: Number,
    F6: Number,
    F7: Number,
    F8: Number,
    F9: Number,
    F10: Number,
    F11: Number,
    F12: Number,
    F13: Number,
    F14: Number,
    F15: Number,
    F16: Number,
    F17: Number,
    F18: Number,
    C1: Number,
    C2: Number,
    C3: Number,
    C4: Number,
    C5: Number,
    C6: Number,
    C7: Number,
    C8: Number,
    C9: Number,
    C10: Number,
    C11: Number,
    C12: Number,
    C13: Number,
    C14: Number,
    C15: Number,
    C16: Number,
    C17: Number,
    C18: Number,
    M1: String,
    M2: String,
    M3: String,
    M4: String,
    M5: String,
    M6: String,
    M7: String,
    M8: String,
    M9: String,
    M10: String,
    M11: String,
    M12: String,
    M13: String,
    M14: String,
    M15: String,
    M16: String,
    M17: String,
    M18: String,
});

module.exports = mongoose.model('Riesgos', riesgosSchema);
