var mongoose = require('mongoose'),
    Schema = mongoose.Schema;
    
var listaSchema = new Schema({
    C1: Boolean,
    C2: Boolean,
    C3: Boolean,
    C4: Boolean,
    C5: Boolean,
    C6: Boolean,
    C7: Boolean,
    C8: Boolean,
    C9: Boolean,
    C10: Boolean,
    C11: Boolean,
    C12: Boolean,
    C13: Boolean,
    C14: Boolean,
    C15: Boolean,
    C16: Boolean,
    C17: Boolean,
    C18: Boolean,
    C19: Boolean,
    C20: Boolean,
    C21: Boolean,
    C22: Boolean,
    C23: Boolean,
    C24: Boolean,
    C25: Boolean,
    C26: Boolean,
    C27: Boolean,
    C28: Boolean,
    C29: Boolean,
    C30: Boolean,
    C31: Boolean,
    C32: Boolean,
    C33: Boolean,
    C34: Boolean,
    C35: Boolean,
    C36: Boolean,
    C37: Boolean,
    C38: Boolean,
    C39: Boolean,
    C40: Boolean,
    C41: Boolean,
    C42: Boolean,
});

module.exports = mongoose.model('Lista', listaSchema);
